#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define CREATE_A_DICTIONNARY 1
#define USE_EXISTING_DICTIONNARY 2
#define MAKE_DICTIONNARY_FROM_FILE 3
#define DESTROY_A_DICTIONNARY 4

#define MYCONSTANT 5
#endif // CONSTANTES_H_INCLUDED
