List * getDifferentWords(char * file, char * dico);
List * compareList(List * first, List * second);
List * generateFakeList();
void replaceWordsInFile (char * file, char * dico);
void putInFile (List * newList, char * dico);
List * replaceWords (List * wordsFile, List * newWords);
void fromListToFile (List * list, char * path);
void printCloseList (char * file, char * dico);
void putCorrectWordsInFIle (char * file, char * dico);
List * getNewWords (List * list, char * dico);
List * putInOrderList(List * list);
List * getEverythingFromFile(char * path);
